import Head from 'next/head'
import Layout from '../components/utils/Layout'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-5xl"> this is a small this</div>
    </Layout>
  )
}
